Areas/Admin/Models/JobModel.cs
using System;
using System.ComponentModel.DataAnnotations;
using Microsoft.AspNetCore.Mvc.ModelBinding.Validation;

namespace VotingApp.Areas.Admin.Models;

public class JobModel
{
    [Key]
    [ValidateNever]
    public int jobId { get; set; }
    public string jobName { get; set; }


}

Areas/Admin/Models/VoteModel.cs
using System;
using System.ComponentModel.DataAnnotations;
using Microsoft.AspNetCore.Mvc.ModelBinding.Validation;

namespace VotingApp.Areas.Admin.Models;

public class VoteModel
{

    [Key]
    [ValidateNever]
    public int voteId { get; set; }


    [Required(ErrorMessage = "Please enter a subject")]
    public string votingSubject { get; set; }


    [Required(ErrorMessage = "Please enter a question")]
    public string votingQuestion { get; set; }

    public List<VoteOptionModel> voteOptions { get; set; } = new List<VoteOptionModel>();

}

Areas/Admin/Models/VoteOptionModel.cs
using System;
using System.ComponentModel.DataAnnotations;
using Microsoft.AspNetCore.Mvc.ModelBinding.Validation;

namespace VotingApp.Areas.Admin.Models;

public class VoteOptionModel
{

    [Key]
    [ValidateNever]
    public int optionId { get; set; }

    [Required(ErrorMessage = "Option is required, please enter a value.")]
    public string optionName { get; set; }

    [ValidateNever]
    public int voteId { get; set; }
    [ValidateNever]
    public VoteModel voteObj { get; set; } = new VoteModel();
    [ValidateNever]
    public List<VoteResultModel> lstResults { get; set; } = new List<VoteResultModel>();
}

Areas/Admin/Models/VoteResultModel.cs
using System;
using System.ComponentModel.DataAnnotations;
using Microsoft.AspNetCore.Mvc.ModelBinding.Validation;

namespace VotingApp.Areas.Admin.Models;

public class VoteResultModel
{
    [Key]
    [ValidateNever]
    public int resultId { get; set; }
    public int optionId { get; set; }
    public int jobId { get; set; }
    public JobModel jobObj { get; set; } = new JobModel();
    public VoteOptionModel optionObj { get; set; } = new VoteOptionModel();
}

Models/ErrorViewModel.cs
namespace VotingApp.Models;

public class ErrorViewModel
{
    public string? RequestId { get; set; }

    public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
}

Areas/Admin/Controllers/VoteController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using VotingApp.Areas.Admin.BusinessLogic;
using VotingApp.Areas.Admin.Models;

namespace VotingApp.Areas.Admin.Controllers
{
    [Area("Admin")]
    public class VoteController : Controller
    {
        private readonly ILogger<VoteController> _logger;

        public VoteController(ILogger<VoteController> logger)
        {
            _logger = logger;
        }

        public IActionResult List()
        {
            return View();
        }
        public IActionResult Edit()
        {
            return View(new VoteModel());
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Save(VoteModel model)
        {

            if (!ModelState.IsValid)
            {
                return View("Edit", model);
            }

            Console.WriteLine("Straight to the database!");
            VoteManager manager = new VoteManager();
            bool saved = manager.Save(model);
            if (saved)
            {
                VoteOptionManager optionManager = new VoteOptionManager();
                foreach (var option in model.voteOptions)
                {
                    option.voteId = model.voteId;
                    option.voteObj = model;
                    optionManager.Save(option);
                }
                Console.WriteLine("All data saved to DB");

            }
            return View("List", model);
        }


        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View("Error!");
        }
    }

}

Controllers/HomeController.cs
using System.Diagnostics;
using Microsoft.AspNetCore.Mvc;
using VotingApp.Models;

namespace VotingApp.Controllers;

public class HomeController : Controller
{
    private readonly ILogger<HomeController> _logger;

    public HomeController(ILogger<HomeController> logger)
    {
        _logger = logger;
    }

    public IActionResult Index()
    {
        return View();
    }

    public IActionResult Privacy()
    {
        return View();
    }

    [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
    public IActionResult Error()
    {
        return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
    }
}

Areas/Admin/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - VotingApp</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/styles.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/css/app.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/VotingApp.styles.css" asp-append-version="true" />
    <link rel="stylesheet"
        href="https://fonts.googleapis.com/css2?family=Material+Symbols+Rounded:opsz,wght,FILL,GRAD@20..48,100..700,0..1,-50..200&icon_names=arrow_forward,arrow_right,delete,double_arrow"
        asp-append-version="true" />
</head>

<body class="bg-c-primary">
    <header>
        @* <nav class="flex h-content relative ">
            <span id="menu-arrow" style="font-size: 1.75rem;"
                class="z-10 material-symbols-rounded  text-white absolute left-[4.6rem] top-6 duration-300 ease-in-out select-none text-2xl">
                double_arrow
            </span>
            <a href="/Vote/List"
                class="z-10 absolute overflow-hidden top-6 left-20 flex justify-start items-start select-none cursor-pointer">
                <span id="admin-nav" class="-translate-x-12 duration-300 hidden ease-in-out text-2xl">
                    Admin
                </span>
            </a>
        </nav> *@
    </header>
    <div>
        <main role="main">
            @RenderBody()
        </main>
    </div>

    <footer class="absolute bottom-0 w-full bg-gray-800 text-white text-center">
        <div class="container">
            &copy; 2025 The Voting App - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.6.0/jquery.min.js"></script>
    @* <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery-validate/1.19.5/jquery.validate.min.js"></script> *@
    @* <script
        src="https://cdnjs.cloudflare.com/ajax/libs/jquery-validation-unobtrusive/3.2.13/jquery.validate.unobtrusive.min.js"></script> *@

    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    <script src="~/js/nav.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>

</html>

Areas/Admin/Views/Vote/Edit.cshtml
@{
    ViewData["Title"] = "Create Votes Page";

}
@model VotingApp.Areas.Admin.Models.VoteModel



@if (Model.voteOptions == null || Model.voteOptions.Count <= 0)
{
    Model.voteOptions = new List<VoteOptionModel> {
new VoteOptionModel { optionName = "" },
new VoteOptionModel { optionName = "" },
new VoteOptionModel { optionName = "" },
new VoteOptionModel { optionName = "" }
};
}

<section id="nav-vote-form"
    class="w-full h-content bg-gradient-to-t from-[#1f2738] to-[#cde1d9] flex flex-row justify-between px-20 py-10 rounded-b-3xl">

    <div class="flex justify-start items-center overflow-hidden">
        <a href="./List" id="user-nav" class="duration-300 ease-in-out text-xl text-c-primary -translate-x-[3rem] ">
            User
        </a>
        <button id="user-menu-arrow" style="font-size: 1.25rem;" class=" material-symbols-rounded -translate-x-[2.5rem] 
             text-c-primary duration-300 ease-in-out select-none text-2xl">
            double_arrow
        </button>
    </div>

    <div class="text-3xl text-c-primary">Vote</div>
    <div class="invisible"></div>
</section>

<section class="bg-white rounded-3xl mx-10 my-20 px-8 py-4 md:w-fit md:mx-auto md:my-10 md:px-5 md:py-8 ">

    <form id="vote-form" class="flex flex-col justify-center items-start gap-4" method="post"
        enctype="multipart/form-data" asp-controller="Vote" asp-action="Save">
        <input type="hidden" asp-for="voteId" />

        <div class="flex flex-col items-start w-full gap-3 md:w-[50rem] md:gap-[1.125rem]">
            <label class="text-xl" for="voting-subject">Voting Subject</label>
            <div class="flex flex-col items-start w-full gap-2">
                <input asp-for="votingSubject"
                    class="w-full text-base px-4 rounded-2xl bg-c-primary text-slate-400 h-14 md:h-16"
                    placeholder="Enter voting subject" type="text" id="voting-subject" />
                <span class="text-red-800" asp-validation-for="votingSubject"></span>
            </div>
        </div>

        <div class="flex flex-col items-start w-full gap-3 md:w-[50rem] md:gap-[1.125rem]">
            <label class="text-xl" for="votingQuestion">Voting Question</label>
            <div class="flex flex-col items-start w-full gap-2">
                <input asp-for="votingQuestion"
                    class="w-full text-base px-4 rounded-2xl bg-c-primary text-slate-400 h-14 md:h-16"
                    placeholder="Enter voting question" type="text" id="votingQuestion" />
                <span class="text-red-800" asp-validation-for="votingQuestion"></span>
            </div>

        </div>

        @for (int i = 0; i < Model.voteOptions.Count; i++)
        {

            <div class="vote-option flex flex-col items-start w-full gap-3 md:w-[50rem] md:gap-[1.125rem]">
                <input type="hidden" asp-for="@Model.voteOptions[i].optionId" />
                <label class="text-xl" for="voting-option">Voting Option @(i + 1)</label>
                <div class="flex flex-col items-start w-full gap-2">
                    <input class="w-full text-base px-4 rounded-2xl bg-c-primary text-slate-400 h-14 md:h-16"
                        placeholder="Enter option @(i + 1)" type="text" asp-for="@Model.voteOptions[i].optionName" />
                    <span class="text-red-800" asp-validation-for="voteOptions[@i].optionName"></span>
                </div>
            </div>
        }

        <div id="form-btn" class="w-full flex justify-start items-start gap-3">
            <input class="w-full text-xl px-5 rounded-2xl bg-orange-300 text-slate-800 h-14 md:h-16" type="submit"
                value="Submit" />
        </div>
    </form>
</section>


@section Scripts {


    <script>



    </script>
}

Areas/Admin/Views/Vote/List.cshtml
@{
    ViewData["Title"] = "Admin Home Page";
}

<section
    class="w-full h-content bg-gradient-to-t from-[#1f2738] to-[#cde1d9] flex flex-col justify-center items-start px-20 py-10 gap-1.5 md:gap-2.5 relative rounded-b-3xl">
    <div class="flex justify-start items-center overflow-hidden">
        <a href="./List" id="user-nav" class="duration-300 ease-in-out text-xl text-c-primary -translate-x-[3rem] ">
            User
        </a>
        <button id="user-menu-arrow" style="font-size: 1.25rem;" class=" material-symbols-rounded -translate-x-[2.5rem] 
             text-c-primary duration-300 ease-in-out select-none text-2xl">
            double_arrow
        </button>
    </div>
    <div class="flex justify-between items-center w-full">
        <h1 class="text-xl text-c-primary">Vote</h1>
        <a href="./Edit" class="flex justify-center items-center text-xl">
            <span class="text-c-primary hidden md:inline">Get more votes</span>
            <span class="material-symbols-rounded text-c-primary">arrow_right</span>
        </a>
    </div>
    <div class="flex flex-col gap-0.5 items-center w-full">
        <h5 class="text-base font-semibold text-c-primary">Total Votes</h5>
        <p class="font-semibold text-xl text-c-primary">80 vote(s)</p>
    </div>


</section>
<div class="relative h-24 flex justify-center items-center ">
    <a id="create-vote-btn" href="./Edit"
        class="w-fit h-content text-2xl px-4 py-3 bg-[#cde1d9] border-8 border-c-primary  rounded-full absolute -top-6 flex justify-center items-center">
        <h4 class="text-[#1f2738]">Create New Vote</h4>
    </a>
</div>


<section id="vote-list" class=" w-full md:w-[75%] m-auto h-content flex flex-col px-32 py-0 gap-8">
    <div class="w-full h-content flex flex-col justify-center items-start bg-neutral-100 px-5 py-8 rounded-3xl">
        <div class="w-content flex justify-center items-center py-2 px-[1.125rem] rounded-full bg-[#DCCFCF]">
            <span>dd/mm/yyyy</span>
        </div>
        <div class="w-full flex justify-between items-center px-[1.125rem]">
            <p>Vote For Best Technology in 2023</p>
            <div class="flex flex-col gap-2 items-center">
                <p>Voters 3000<sub>/votes</sub></p>
                <div class="w-content flex justify-center items-center py-2 px-[1.125rem] rounded-full bg-[#DCCFCF]">
                    <span>show my result</span>
                </div>
            </div>
        </div>
    </div>
</section>


@section Scripts {
    <script>
        document.addEventListener('DOMContentLoaded', () => {
            const menuArrow = document.getElementById('menu-arrow');
            const adminLink = document.getElementById('admin-nav');

            menuArrow.addEventListener('mousedown', () => {
                menuArrow.classList.toggle('-translate-x-[3.56rem]');

                setTimeout(() => {
                    menuArrow.classList.toggle('duration-300');
                    menuArrow.classList.toggle('rotate-180');

                    setTimeout(() => {
                        menuArrow.classList.toggle('duration-300');
                    }, 100);
                }, 350);

                setTimeout(() => {
                    adminLink.classList.toggle('-translate-x-[3.56rem]');
                }, 100);
            });
        });
    </script>
}

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - VotingApp</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/styles.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/css/app.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/VotingApp.styles.css" asp-append-version="true" />
    <link rel="stylesheet"
        href="https://fonts.googleapis.com/css2?family=Material+Symbols+Rounded:opsz,wght,FILL,GRAD@20..48,100..700,0..1,-50..200&icon_names=arrow_forward,arrow_right,delete,double_arrow"
        asp-append-version="true" />
</head>

<body class="bg-c-primary">
    <header>
        @* <nav class="flex h-content relative ">
            <span id="menu-arrow" style="font-size: 1.75rem;"
                class="z-10 material-symbols-rounded  text-white absolute left-[4.6rem] top-6 duration-300 ease-in-out select-none text-2xl">
                double_arrow
            </span>
            <a href="/Vote/List"
                class="z-10 absolute overflow-hidden top-6 left-20 flex justify-start items-start select-none cursor-pointer">
                <span id="admin-nav" class="-translate-x-12 duration-300 hidden ease-in-out text-2xl">
                    Admin
                </span>
            </a>
        </nav> *@
    </header>
    <div>
        <main role="main">
            @RenderBody()
        </main>
    </div>

    <footer class="absolute bottom-0 w-full bg-gray-800 text-white text-center">
        <div class="container">
            &copy; 2025 The Voting App - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.6.0/jquery.min.js"></script>
    @* <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery-validate/1.19.5/jquery.validate.min.js"></script> *@
    @* <script
        src="https://cdnjs.cloudflare.com/ajax/libs/jquery-validation-unobtrusive/3.2.13/jquery.validate.unobtrusive.min.js"></script> *@

    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    <script src="~/js/nav.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>

</html>